openapi: 3.0.3
info:
  title: "JarsoftTest API"
  description: "Simple ad banner app API"
  version: 1.0.0
  contact:
    name: "Pavel Vasilev"
    url: "https://t.me/LovelySharkPlush"
    email: "p.vasilev@g.nsu.ru"

servers:
  - url: 'https://localhost:8080/'
    description: "The default server url"

paths:
  /api/category/all:
    get:
      responses:
        200:
          description: "all the categories"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref:
                    "schemas.yaml#/components/schemas/Category"
        default:
          $ref: "#/components/responses/UnknownError"

  /api/category/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int64
        required: true

    put:
      parameters:
        - $ref: "params.yaml/#/components/parameters/Name"
        - $ref: "params.yaml/#/components/parameters/RequestId"
      description: "update a category with given id"
      responses:
        200:
          description: "category successfully updated"
        409:
          description: "category can't have given name or requestId (they have to be unique)"

    delete:
      description: "delete a category with given id"
      responses:
        200:
          description: "OK"
        404:
          description: "the category with this id doesn't exist or was already deleted"
        409:
          description: "can't delete a category that is connected to existing banner"

    get:
      description: "get a category with given id"
      responses:
        200:
          description: "OK"
        404:
          description: "the category with this id doesn't exist or was already deleted"

  /api/category/new:
    post:
      parameters:
        - $ref: "params.yaml/#/components/parameters/Name"
        - $ref: "params.yaml/#/components/parameters/RequestId"
      responses:
        200:
          description: "category successfully created"
          content:
            application/json:
              schema:
                type: integer
                format: int64
        409:
          description: "can't create category with this name or requestId (they have to be unique)"

  /api/banner/ids_and_names:
    get:
      responses:
        200:
          description: "all the ids and names of banners"
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/IdNameArray"
        default:
          $ref: "#/components/responses/UnknownError"


  /api/banner/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64

    get:
      responses:
        200:
          description: "data associated with a banner with given id"
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/Banner"
        404:
          description: "banner with this id doesn't exist or was deleted"
        default:
          $ref: "#/components/responses/UnknownError"

    put:
      description: "update a banner with a given id"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/BannerWithoutId"
      responses:
        200:
          description: "banner successfully updated"
        404:
          description: "banner with this id doesn't exist"
        409:
          description: "can't change banner name because banner with that name already exists"
        default:
          $ref: "#/components/responses/UnknownError"

    delete:
      responses:
        200:
          description: "banner successfully deleted"
        404:
          description: "banner with this id doesn't exist"
        default:
          $ref: "#/components/responses/UnknownError"

  /api/banner/new:
    post:
      requestBody:
        description: "new banner to be created"
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/BannerWithoutId"
      responses:
        200:
          description: "banner successfully created"
          content:
            application/json:
              schema:
                type: integer
                format: int64
        409:
          description: "can't create with given name (it has to be unique)"

  /api/bid:
    get:
      parameters:
        - name: cat
          in: query
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      responses:
        200:
          description: "valid banner was found successfully"
        204:
          description: "no banner was found"

  /api/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/Login"
      responses:
        200:
          description: "authenticated successfully"
          headers:
            JWT:
              description: "JWT associated with the login"
              content:
                plain/text:
                  schema:
                    type: string
        401:
          description: "authentication failed"




components:
  responses:
    UnknownError:
      description: "unexpected error has occurred"
